// <auto-generated />
using System;
using Ledger.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Ledger.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(LedgerDbContext))]
    partial class LedgerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Ledger.Domain.Entities.Invoice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CustomerReference")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("customer_reference");

                    b.HasKey("Id");

                    b.ToTable("invoices", (string)null);
                });

            modelBuilder.Entity("Ledger.Domain.Entities.InvoiceLineItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("description");

                    b.Property<DateOnly>("DueDate")
                        .HasColumnType("date")
                        .HasColumnName("due_date");

                    b.Property<Guid>("InvoiceId")
                        .HasColumnType("uuid")
                        .HasColumnName("invoice_id");

                    b.Property<decimal>("OriginalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("original_amount");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceId", "DueDate", "CreatedAt", "Id")
                        .HasDatabaseName("ix_invoice_line_items_invoice_oldest_first");

                    b.ToTable("invoice_line_items", null, t =>
                        {
                            t.HasCheckConstraint("ck_invoice_line_items_original_amount_positive", "original_amount > 0");

                            t.HasCheckConstraint("ck_invoice_line_items_original_amount_scale", "round(original_amount, 2) = original_amount");
                        });
                });

            modelBuilder.Entity("Ledger.Domain.Entities.LedgerEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("amount");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("EntryType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("entry_type");

                    b.Property<Guid>("InvoiceId")
                        .HasColumnType("uuid")
                        .HasColumnName("invoice_id");

                    b.Property<Guid?>("InvoiceLineItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("invoice_line_item_id");

                    b.Property<Guid?>("PaymentId")
                        .HasColumnType("uuid")
                        .HasColumnName("payment_id");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceId")
                        .HasDatabaseName("ix_ledger_entries_invoice_id");

                    b.HasIndex("InvoiceLineItemId")
                        .HasDatabaseName("ix_ledger_entries_invoice_line_item_id");

                    b.HasIndex("PaymentId")
                        .HasDatabaseName("ix_ledger_entries_payment_id");

                    b.ToTable("ledger_entries", null, t =>
                        {
                            t.HasCheckConstraint("ck_ledger_entries_amount_non_zero", "amount <> 0");

                            t.HasCheckConstraint("ck_ledger_entries_amount_scale", "round(amount, 2) = amount");

                            t.HasCheckConstraint("ck_ledger_entries_charge_positive", "entry_type <> 'Charge' OR amount > 0");

                            t.HasCheckConstraint("ck_ledger_entries_credit_has_no_line", "entry_type <> 'CustomerCredit' OR invoice_line_item_id IS NULL");

                            t.HasCheckConstraint("ck_ledger_entries_line_entries_have_line", "entry_type = 'CustomerCredit' OR invoice_line_item_id IS NOT NULL");

                            t.HasCheckConstraint("ck_ledger_entries_payments_negative", "entry_type = 'Charge' OR amount < 0");
                        });
                });

            modelBuilder.Entity("Ledger.Domain.Entities.InvoiceLineItem", b =>
                {
                    b.HasOne("Ledger.Domain.Entities.Invoice", "Invoice")
                        .WithMany("LineItems")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Invoice");
                });

            modelBuilder.Entity("Ledger.Domain.Entities.LedgerEntry", b =>
                {
                    b.HasOne("Ledger.Domain.Entities.Invoice", "Invoice")
                        .WithMany()
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Ledger.Domain.Entities.InvoiceLineItem", "InvoiceLineItem")
                        .WithMany()
                        .HasForeignKey("InvoiceLineItemId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Invoice");

                    b.Navigation("InvoiceLineItem");
                });

            modelBuilder.Entity("Ledger.Domain.Entities.Invoice", b =>
                {
                    b.Navigation("LineItems");
                });
#pragma warning restore 612, 618
        }
    }
}
